### ISSUE TITLE
New Slack theme config

### ISSUE THREAD

**Issue by pablopunk** [catppuccin/slack#2]
The new slack UI themes consist of only 4 colors, so catppuccin is not compatible anymore

### Pasting a theme into a message
![CleanShot 2023-09-21 at 10 15 11@2x](https://github.com/catppuccin/slack/assets/4324982/24530ba1-600b-4605-8e8d-d9eae806def1)

### Manual config
<img width="830" alt="image" src="https://github.com/catppuccin/slack/assets/4324982/5f1132de-bdc1-4a6a-a9ac-a6a5f116edab">

**Comment by pablopunk** [comment]
Also I've entered 4 custom colors (from Catppuccin's palette) but it doesn't seem to recognize it as a theme, not sure if they allow colors outside their palette

**Comment by mjr2595** [comment]
The new Slack UI's theming is such a huge downgrade. I submitted some feedback and requested the Slack team respond back, but I'm guessing I'll just a generic "Thanks, we got your feedback" type of reply. Custom color themes are simply gone now. Current [help page](https://slack.com/help/articles/205166337-Change-your-Slack-theme) for editing themes does not mention custom colors.

Edit: Got a reply from Slack Support

> We have been receiving a lot of feedback about the new layout and ability to fully customise. That said, I'm happy to share that we are working on bringing back the ability to select custom colours. I don't have a timeframe, but it's in active development.

**Comment by pablopunk** [comment]
thanks @mjr2595! Looking forward to that

**Comment by sgtxn** [comment]
Looks like Slack supports importing old themes now, the theme string from this repo worked fine for me  

<details>
<summary>Screenshots</summary>  

![image](https://github.com/catppuccin/slack/assets/40335856/09d21ff3-aaf5-4d52-914d-35f9df9220dd)  

![image](https://github.com/catppuccin/slack/assets/40335856/c9e71ed9-662e-419f-8c1c-727fe3c9de9d)  

</details>

UPD: the channel selection color is kinda weird though, I think it used to be different before  

![image](https://github.com/catppuccin/slack/assets/40335856/9aa0949f-abcf-432b-9411-fef13849926f)

**Comment by pablopunk** [comment]
awesome @sgtxn !
